# Generated by Django 4.1.1 on 2022-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_initial"),
        ("rooms", "0002_initial"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experience",
            field=models.ManyToManyField(to="experiences.experience"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(to="rooms.room"),
        ),
    ]
